spring:
  application:
    name: backend

  # MariaDB 연결 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/account_book_db}
    username: ${SPRING_DATASOURCE_USERNAME:account}
    password: ${SPRING_DATASOURCE_PASSWORD:book}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.tickle_moa.backend
  configuration:
    map-underscore-to-camel-case: true

# JWT 설정
jwt:
  secret: /TX6txOQJw4rDYj82onjCbwfZYEQpod3MA9L5mRMbhyG4laOFt1/asEEdUNFkv+EE47eQiB/LdTvLdsryc3RIQ==
  expiration: 1800000       # 30 minutes (accessToken 만료 시간)
  refresh-expiration: 604800000  # 1 week (refreshToken 만료 시간)

# 서버 포트
server:
  port: 8080
