spring:
  application:
    name: backend

  # MariaDB 연결 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/account_book_db
    username: account
    password: book

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.backend
  configuration:
    map-underscore-to-camel-case: true

# 서버 설정
server:
  port: 8080
